In [84]:
import pandas as pd

In [85]:
#Manually set data types by column import
data_types = {
    "First Name":"str"
}

#Set aside which column imports will be dates
date_cols=["Fiscal Year", "Agency Start Date"]

#Load CSV and set preconditions
data = pd.read_csv(
    '../input/Citywide_Payroll_Data_(Fiscal_Year)_20261013.csv',
    low_memory=False,
    #Manually set data types
    dtype=data_types,
    #Parse date columns as dates
    parse_dates=date_cols
    )
len(data)
data.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,ZAFFARANO,CHRISTINE,NaN,04/11/2016,MANHATTAN,AGENCY ATTORNEY,CEASED,"$91,563.00",per Annum,35,"$1,755.85",0,$0.00,$95.05
1,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,WRIGHT,TREMAINE,O,08/29/2016,MANHATTAN,COMMUNITY COORDINATOR,ACTIVE,"$78,450.00",per Annum,"1,820","$78,361.19",0,$0.00,"$3,000.00"
2,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,XAVIER,CALLYANN,M,05/22/2017,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ACTIVE,"$65,921.00",per Annum,"1,820","$65,998.30",285.75,"$13,732.03","$12,901.84"
3,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,WILSON,DESIREE,NaN,02/06/2017,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ACTIVE,"$65,921.00",per Annum,"1,820","$65,791.47",41,"$1,595.59","$12,672.67"
4,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,WILSON,GEOFFREY,M,06/15/2009,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ACTIVE,"$65,921.00",per Annum,"1,820","$65,837.61",0,$9.89,"$14,532.71"

In [86]:
#Get column length idk why
len(data.columns)

17

In [87]:
#Examine data types
data.dtypes

Fiscal Year                   datetime64[ns]
Payroll Number                         int64
Agency Name                           object
Last Name                             object
First Name                            object
Mid Init                              object
Agency Start Date                     object
Work Location Borough                 object
Title Description                     object
Leave Status as of June 30            object
Base Salary                           object
Pay Basis                             object
Regular Hours                         object
Regular Gross Paid                    object
OT Hours                              object
Total OT Paid                         object
Total Other Pay                       object
dtype: object

In [88]:
#We can use .value_counts() to do a quick 'pivot table' of any given column

data["Title Description"].value_counts()

Title Description
TEACHER- PER SESSION                                   79950
TEACHER                                                56489
ELECTION WORKER                                        29686
TEACHER SPECIAL EDUCATION                              29228
ANNUAL ED PARA                                         28225
                                                       ...
DIR OF HOME CARE SERVICES/FAMILY AND ADULT SERVICES        1
DIR OF MGNT SYSTEM, PLANNING, RESEARCH AND EVAL            1
ASS COMMISSIONER DESIGN AND CONSTRUCTION MANAGEMENT        1
DEPUTY COMMISSIONER FOR POLICY AND ANALYSIS                1
First Deputy Commissioner                                  1
Name: count, Length: 1535, dtype: int64

In [89]:
#We can use .describe() to get an overview of the data in each column.
# The function reveals various chracteristics of your data column.
# count/med/mean/std/min/25%/50%/75%/max/column_name

data["Base Salary"].describe()

count     552938
unique     34557
top       $33.18
freq       79825
Name: Base Salary, dtype: object

In [90]:
data.columns

data["Pay Basis"].value_counts()

Pay Basis
per Annum          338552
per Day            124341
per Hour            87696
Prorated Annual      2349
Name: count, dtype: int64

In [91]:
# logic operators return a boolean (true/false conditions)

# Return only the salaried employees by filtering for per Annum pay entries

data_reduced = data[data["Pay Basis"] == "per Annum"]

print(len(data_reduced))
print(len(data))

print(f"Rows in reduced dataset: {len(data_reduced)}. Rows in full dataset: {len(data)}.")

338552
552938
Rows in reduced dataset: 338552. Rows in full dataset: 552938.

In [92]:
# lambda lowkey means function -- initializes function
# one line of code to run through a whole dataset brrr

# Look at pay basis column values, lowercase it, 
# remove whitespace, and see if per annum is in that string. 
# Then put the true/false result in a new column, is_per_annum

# Value in Pay Basis column is being assigned to x

data["is_per_annum"] = data["Pay Basis"].apply(lambda x: "per annum" in str(x).lower())

data.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,is_per_annum
0,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,ZAFFARANO,CHRISTINE,NaN,04/11/2016,MANHATTAN,AGENCY ATTORNEY,CEASED,"$91,563.00",per Annum,35,"$1,755.85",0,$0.00,$95.05,True
1,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,WRIGHT,TREMAINE,O,08/29/2016,MANHATTAN,COMMUNITY COORDINATOR,ACTIVE,"$78,450.00",per Annum,"1,820","$78,361.19",0,$0.00,"$3,000.00",True
2,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,XAVIER,CALLYANN,M,05/22/2017,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ACTIVE,"$65,921.00",per Annum,"1,820","$65,998.30",285.75,"$13,732.03","$12,901.84",True
3,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,WILSON,DESIREE,NaN,02/06/2017,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ACTIVE,"$65,921.00",per Annum,"1,820","$65,791.47",41,"$1,595.59","$12,672.67",True
4,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,WILSON,GEOFFREY,M,06/15/2009,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ACTIVE,"$65,921.00",per Annum,"1,820","$65,837.61",0,$9.89,"$14,532.71",True

In [94]:
#First need to convert to numeric bc my code is being weird

data["Base Salary"] = (
    data["Base Salary"]
    .astype(str)
    .str.replace(r"[$,]", "", regex=True)
    .str.strip()
)
data["Base Salary"] = pd.to_numeric(data["Base Salary"], errors="coerce")

In [97]:
# Get median pay per job position by using groupby
# and applying same function to each job type

# Group by Title Description and identify its Base Salary column
# as the one we want to use for our calculations.
#Then take mean

data.groupby(
    ["Title Description"]
)["Base Salary"].median(

).reset_index(

).sort_values(
    by="Base Salary",
    ascending=False
)

                    Title Description  Base Salary
358                        CHANCELLOR    363346.00
364                     CHIEF ACTUARY    318442.50
1130                        PRESIDENT    280908.00
907                FIRST DEPUTY MAYOR    275000.00
1055                            MAYOR    258750.00
...                               ...          ...
1396           SUBSTITUTE SCHOOL AIDE        14.37
1397   SUBSTITUTE SCHOOL LUNCH HELPER        14.37
1395  SUBSTITUTE RECREATION ASSISTANT        14.00
789                   ELECTION WORKER         1.00
788                  ELECTION TRAINER         1.00

[1535 rows x 2 columns]

In [ ]:
data[data["Title Description"] == "PRESIDENT"]

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,is_per_annum
46052,2023-01-01,463,COMMUNITY COLLEGE (BRONX),ISEKENEGBE,THOMAS,A,08/17/2015,QUEENS,PRESIDENT,ACTIVE,280908.0,per Annum,"1,820","$285,256.42",0,$0.00,"$60,000.00",True
46860,2023-01-01,468,COMMUNITY COLLEGE (HOSTOS),COCCO DE FILIPP,DAISY,NaN,01/15/2002,BRONX,PRESIDENT,ACTIVE,283560.0,per Annum,"1,820","$282,706.86",0,$0.00,"$60,000.00",True
49709,2023-01-01,465,COMMUNITY COLLEGE (KINGSBORO),SCHRADER,CLAUDIA,NaN,09/15/2018,BROOKLYN,PRESIDENT,ACTIVE,280908.0,per Annum,"1,820","$285,256.90",0,$0.00,"$60,000.00",True
52334,2023-01-01,469,COMMUNITY COLLEGE (LAGUARDIA),ADAMS,KENNETH,G,08/17/2020,QUEENS,PRESIDENT,ACTIVE,280908.0,per Annum,"1,820","$285,389.05",0,$0.00,"$60,000.00",True
56793,2023-01-01,466,COMMUNITY COLLEGE (MANHATTAN),MUNROE,ANTHONY,E,09/01/2020,MANHATTAN,PRESIDENT,ACTIVE,280500.0,per Annum,"1,820","$279,656.06",0,$0.00,"$60,000.00",True
58546,2023-01-01,464,COMMUNITY COLLEGE (QUEENSBORO),MANGINO,CHRISTINE,NaN,08/17/2020,QUEENS,PRESIDENT,ACTIVE,280908.0,per Annum,"1,820","$285,389.05",0,$0.00,"$60,000.00",True
451394,2023-01-01,462,GUTTMAN COMMUNITY COLLEGE,JOHNSON,LARRY,D,07/01/2021,MANHATTAN,PRESIDENT,ACTIVE,260100.0,per Annum,"1,820","$259,317.57",0,$0.00,"$60,000.00",True
549584,2023-01-01,21,TAX COMMISSION,HENN,FRANCES,J,05/02/2016,MANHATTAN,PRESIDENT,ACTIVE,227786.0,per Annum,"1,820","$227,161.99",0,$0.00,$375.00,True

In [115]:
data.groupby(
    ["Agency Name", "Work Location Borough"]
)["Base Salary"].median(

).reset_index(

).sort_values(
    by="Base Salary",
    ascending=False
)

                        Agency Name Work Location Borough  Base Salary
259             OFFICE OF THE MAYOR         WASHINGTON DC    154000.00
69    COMMUNITY COLLEGE (LAGUARDIA)                 BRONX    152939.00
181  DISTRICT ATTORNEY-SPECIAL NARC              BROOKLYN    145000.00
183  DISTRICT ATTORNEY-SPECIAL NARC                QUEENS    141250.00
250  OFFICE OF COLLECTIVE BARGAININ             MANHATTAN    140000.00
..                              ...                   ...          ...
274            PUBLIC SERVICE CORPS             MANHATTAN        16.00
166      DEPT OF PARKS & RECREATION           WESTCHESTER        15.91
260              PERSONNEL MONITORS             MANHATTAN        15.00
16   BOARD OF ELECTION POLL WORKERS              BROOKLYN         1.00
17   BOARD OF ELECTION POLL WORKERS             MANHATTAN         1.00

[300 rows x 3 columns]