### Homework 5: Pandas Practice

For this homework, you'll be using Pandas to analyze a database of fatal police shootings in the US.

In [270]:
import pandas as pd

In [271]:
data = pd.read_csv("fatal-police-shootings-data.csv",
                   parse_dates=["date"])

In [272]:
data.dtypes

id                                     int64
date                          datetime64[ns]
threat_type                           object
flee_status                           object
armed_with                            object
city                                  object
county                                object
state                                 object
latitude                             float64
longitude                            float64
location_precision                    object
name                                  object
age                                  float64
gender                                object
race                                  object
race_source                           object
was_mental_illness_related              bool
body_camera                             bool
agency_ids                            object
dtype: object

In [273]:
data.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,A,not_available,True,False,73
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,W,not_available,False,False,70
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,H,not_available,False,False,238
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,W,not_available,True,False,196
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,H,not_available,False,False,473

Spend some time examining the columns in the data to get a little familiar with the information you're working with...

In [274]:
len(data)

10430

In [275]:
# What is the time range of the available data? Use a line of pandas code to find out.

# Minimum
min_date = data['date'].min()
print(min_date)

# Maximum
max_date = data['date'].max()
print(max_date)

2015-01-02 00:00:00
2024-12-31 00:00:00

In [276]:
# Say you want to analyze the racial disparities in this dataset, broken down
# by race and by the larger category of non-white people.

# Write a line of code that takes a look at the universe of values in the race column.


# Get all values in column

race_values = data['race'].unique().tolist()
print(race_values)

['A', 'W', 'H', 'B', 'O', nan, 'N', 'W;B;N', 'N;H', 'W;H', 'B;H', 'W;B', 'W;A']

In [ ]:
# Make the letters in the race column all lower-case -- Lylla version

data['race'] = data['race'].str.lower()

# 
# 
# 

#data["race_lowercase"] = data["race"].str.lower()
#data.head()

#race_lowercase_values = data['race_lowercase'].unique().tolist()
#print(race_lowercase_values)

['a', 'w', 'h', 'b', 'o', nan, 'n', 'w;b;n', 'n;h', 'w;h', 'b;h', 'w;b', 'w;a']

In [278]:
# Create a new column called "poc" and use a lambda function to set 
# it equal to True or False based on the information in the race column.

# How many rows are POC and how many are White?

# Make a POC column and mark entries as "true" if they are POC
data["race_poc"] = data["race_lowercase"].apply(lambda x: str(x).lower() != "w")

# Count
data["race_poc"].value_counts(dropna=True)

race_poc
True     5771
False    4659
Name: count, dtype: int64

Therefore, 5,771 entries are POC (or white and another value), and 4,659 are white.

In [279]:
# I want to know which county had the most police killings but some counties in the U.S. 
# have the same name. 

# Create a column called country_state and populate it with the county and the state to 
# create unique pairs. 


# Now answer the question: which county had the most killings?

# Concatenate county and state data
data["county_state"] = data["county"] + ' ' + data["state"]

# Count entries per county_state value
data["county_state"].value_counts(dropna=True)

county_state
Los Angeles CA       222
Maricopa AZ          151
Harris TX             96
San Bernardino CA     79
Bexar TX              64
                    ...
Sabine LA              1
Nelson KY              1
New Madrid MO          1
Iowa IA                1
Rolette ND             1
Name: count, Length: 1401, dtype: int64

Therefore, Los Angeles County, CA had the most killings with 222.

In [280]:
# Create a new column called "unarmed" and use a lambda function to set it to True/False based on the relevant info.

# Create a subset of the data for unarmed killings and store it in a new variable called unarmed_killings. 

# Which county had the most of these?


# Create new column
data["unarmed"] = data["armed_with"].apply(lambda x: str(x).lower() == "unarmed")


# Create new data subset
unarmed_killings = []

# Append w relevant data
for index, row in data.iterrows():
    if row["unarmed"] == True:
        unarmed_killings.append(row)

# Check work
unarmed_killings_df = pd.DataFrame(unarmed_killings)
unarmed_killings_df["armed_with"].value_counts(dropna=True)

armed_with
unarmed    565
Name: count, dtype: int64

In [281]:
# We could have done that more smoothly using a groupby. So let's do that. 
# Group the original dataset by your new columns unarmed killings and county_state. 
# Use loc[] to isolate the rows where unarmed==True
# Sort from highest #killings to lowest

data.loc[data["unarmed"] == True].groupby(
    ["county_state"]
).size().reset_index(
    name="count"
).sort_values(
    by="count",
    ascending=False
)

          county_state  count
113     Los Angeles CA     19
136          Orange CA      7
117        Maricopa AZ      6
169  San Bernardino CA      6
170       San Diego CA      6
..                 ...    ...
83          Hancock OH      1
87         Hartford CT      1
88           Hawaii HI      1
89        Henderson TN      1
109          Laurel KY      1

[219 rows x 2 columns]

I want to examine the data by race and gender to understand whether Black women are disproportionately killed by the police compared to white women and by how much. I'm not going to tell you what to do beyond that — this is where you need to think creatively as a data reporter! What information do you need to look up to figure out this answer? Go step by step and show your working using Python comments.

In [282]:
# Declare a list

women_only = []

# Append w relevant data
for index, row in data.iterrows():
    if row["gender"] == "female":
        women_only.append(row)

#Check work
women_only_count = pd.DataFrame(women_only)
women_only_count["gender"].value_counts(dropna=True)

# Return counts by race
women_only_count["race"].value_counts()

race
W      254
B       88
H       59
A       11
N        8
O        4
N;H      1
Name: count, dtype: int64

In [283]:
# Based on returned values, store in variables
# (add +1 to Hispanic and Native bc one person is labeled N;H)
white_women_count = (women_only_count["race"].str.lower() == "w").sum()
black_women_count = (women_only_count["race"].str.lower() == "b").sum()
hisp_women_count = ((women_only_count["race"].str.lower() == "h").sum() + 1)
asian_women_count = (women_only_count["race"].str.lower() == "a").sum()
native_women_count = ((women_only_count["race"].str.lower() == "n").sum() + 1)
other_women_count = (women_only_count["race"].str.lower() == "o").sum()

print(white_women_count, black_women_count, hisp_women_count, asian_women_count, native_women_count, other_women_count)

254 88 60 11 9 4

In [284]:
# Import U.S. women populations by race in 2024 (most recent year in dataset)
# Source: U.S. Census Bureau (https://www.census.gov/programs-surveys/popest.html)

white_women_pop = 128475000
black_women_pop = 24100000
hisp_women_pop = 31800000
asian_women_pop = 11900000
native_women_pop = 2400000

# Calculate number of killings per racial group

white_women_rate = white_women_count / white_women_pop
black_women_rate = black_women_count / black_women_pop
hisp_women_rate = hisp_women_count / hisp_women_pop
asian_women_rate = asian_women_count / asian_women_pop
native_women_rate = native_women_count / native_women_pop

# Store in a dataframe
dataWomenByRace = pd.DataFrame({
    "Race": ["White", "Black", "Hispanic", "Asian", "Native"],
    "Pop": [white_women_pop, black_women_pop, hisp_women_pop, asian_women_pop, native_women_pop],
    "Killings": [white_women_count, black_women_count, hisp_women_count, asian_women_count, native_women_count],
    "Rate": [white_women_rate, black_women_rate, hisp_women_rate, asian_women_rate, native_women_rate]
})

# Sort bty rate (commented out)
# dataWomenByRace.sort_values(by="Rate", ascending=False)

# Calculate how much more Black women are killed than white women
comparison = black_women_rate / white_women_rate

print(f"Between 2014 and 2025, Black women were killed by police at {comparison} times the rate of white women.")

Between 2014 and 2025, Black women were killed by police at 1.8469304407488485 times the rate of white women.

Your editor wants you to examine mental illness in police killings in the US by state. Seeing which state had the most killings of mentally ill people is not enough; you'll need to scale by population. To do that, you will use the Python census library to access Census data. You'll need an API key to use it.

Sign up for a Census API key at this website: https://api.census.gov/data/key_signup.html 

Then check your email to get the API key. Make sure to click the activation link in the email.

In [285]:
# install the python census library.
%pip install census
%pip install geonamescache

Requirement already satisfied: census in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (0.8.27)
Requirement already satisfied: requests>=1.1.0 in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (from census) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (from requests>=1.1.0->census) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (from requests>=1.1.0->census) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (from requests>=1.1.0->census) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (from requests>=1.1.0->census) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: geonamescache in /Users/jackwalker/Data/2026/CUNY_fall/CUNY_adv-data/.venv/lib/python3.9/site-packages (2.0.0)
Note: you may need to restart the kernel to use updated packages.

### TAKE A BREAK!

It can take several minutes for your API key to be activated. Go have a stretch, get some water, etc...

In [286]:
# Edited in my own API key

api_key = "f333fb15dbddc4e2f104ee782f154fc6960782bc"

In [287]:
import os
from census import Census
from us import states
import geonamescache

In [288]:
gc = geonamescache.GeonamesCache()
us_states = gc.get_us_states()

# The geonamescache library stores the fips code for each state. 
# Adjust the loop I have below to populate the empty dictionary below, 
# where the keys are state codes (i.e. AK) and the values are fips codes (as strings)

state_to_fips = {}


for state_code, state_info in us_states.items():
    print(state_info)

{'code': 'AK', 'name': 'Alaska', 'fips': '02', 'geonameid': 5879092}
{'code': 'AL', 'name': 'Alabama', 'fips': '01', 'geonameid': 4829764}
{'code': 'AR', 'name': 'Arkansas', 'fips': '05', 'geonameid': 4099753}
{'code': 'AZ', 'name': 'Arizona', 'fips': '04', 'geonameid': 5551752}
{'code': 'CA', 'name': 'California', 'fips': '06', 'geonameid': 5332921}
{'code': 'CO', 'name': 'Colorado', 'fips': '08', 'geonameid': 5417618}
{'code': 'CT', 'name': 'Connecticut', 'fips': '09', 'geonameid': 4831725}
{'code': 'DC', 'name': 'District of Columbia', 'fips': '11', 'geonameid': 4138106}
{'code': 'DE', 'name': 'Delaware', 'fips': '10', 'geonameid': 4142224}
{'code': 'FL', 'name': 'Florida', 'fips': '12', 'geonameid': 4155751}
{'code': 'GA', 'name': 'Georgia', 'fips': '13', 'geonameid': 4197000}
{'code': 'HI', 'name': 'Hawaii', 'fips': '15', 'geonameid': 5855797}
{'code': 'IA', 'name': 'Iowa', 'fips': '19', 'geonameid': 4862182}
{'code': 'ID', 'name': 'Idaho', 'fips': '16', 'geonameid': 5596512}
{'code': 'IL', 'name': 'Illinois', 'fips': '17', 'geonameid': 4896861}
{'code': 'IN', 'name': 'Indiana', 'fips': '18', 'geonameid': 4921868}
{'code': 'KS', 'name': 'Kansas', 'fips': '20', 'geonameid': 4273857}
{'code': 'KY', 'name': 'Kentucky', 'fips': '21', 'geonameid': 6254925}
{'code': 'LA', 'name': 'Louisiana', 'fips': '22', 'geonameid': 4331987}
{'code': 'MA', 'name': 'Massachusetts', 'fips': '25', 'geonameid': 6254926}
{'code': 'MD', 'name': 'Maryland', 'fips': '24', 'geonameid': 4361885}
{'code': 'ME', 'name': 'Maine', 'fips': '23', 'geonameid': 4971068}
{'code': 'MI', 'name': 'Michigan', 'fips': '26', 'geonameid': 5001836}
{'code': 'MN', 'name': 'Minnesota', 'fips': '27', 'geonameid': 5037779}
{'code': 'MO', 'name': 'Missouri', 'fips': '29', 'geonameid': 4398678}
{'code': 'MS', 'name': 'Mississippi', 'fips': '28', 'geonameid': 4436296}
{'code': 'MT', 'name': 'Montana', 'fips': '30', 'geonameid': 5667009}
{'code': 'NC', 'name': 'North Carolina', 'fips': '37', 'geonameid': 4482348}
{'code': 'ND', 'name': 'North Dakota', 'fips': '38', 'geonameid': 5690763}
{'code': 'NE', 'name': 'Nebraska', 'fips': '31', 'geonameid': 5073708}
{'code': 'NH', 'name': 'New Hampshire', 'fips': '33', 'geonameid': 5090174}
{'code': 'NJ', 'name': 'New Jersey', 'fips': '34', 'geonameid': 5101760}
{'code': 'NM', 'name': 'New Mexico', 'fips': '35', 'geonameid': 5481136}
{'code': 'NV', 'name': 'Nevada', 'fips': '32', 'geonameid': 5509151}
{'code': 'NY', 'name': 'New York', 'fips': '36', 'geonameid': 5128638}
{'code': 'OH', 'name': 'Ohio', 'fips': '39', 'geonameid': 5165418}
{'code': 'OK', 'name': 'Oklahoma', 'fips': '40', 'geonameid': 4544379}
{'code': 'OR', 'name': 'Oregon', 'fips': '41', 'geonameid': 5744337}
{'code': 'PA', 'name': 'Pennsylvania', 'fips': '42', 'geonameid': 6254927}
{'code': 'RI', 'name': 'Rhode Island', 'fips': '44', 'geonameid': 5224323}
{'code': 'SC', 'name': 'South Carolina', 'fips': '45', 'geonameid': 4597040}
{'code': 'SD', 'name': 'South Dakota', 'fips': '46', 'geonameid': 5769223}
{'code': 'TN', 'name': 'Tennessee', 'fips': '47', 'geonameid': 4662168}
{'code': 'TX', 'name': 'Texas', 'fips': '48', 'geonameid': 4736286}
{'code': 'UT', 'name': 'Utah', 'fips': '49', 'geonameid': 5549030}
{'code': 'VA', 'name': 'Virginia', 'fips': '51', 'geonameid': 6254928}
{'code': 'VT', 'name': 'Vermont', 'fips': '50', 'geonameid': 5242283}
{'code': 'WA', 'name': 'Washington', 'fips': '53', 'geonameid': 5815135}
{'code': 'WI', 'name': 'Wisconsin', 'fips': '55', 'geonameid': 5279468}
{'code': 'WV', 'name': 'West Virginia', 'fips': '54', 'geonameid': 4826850}
{'code': 'WY', 'name': 'Wyoming', 'fips': '56', 'geonameid': 5843591}

In [289]:
# Ping the Census API with your key...
c = Census(api_key, year=2023)

# We're using American Community Survey Version 5 (acs5 in the census library)
# Population is represented by data code "B01003_001E"
# So to pull the population for New York state, which is FIPS code 36, here's what you do:

ny_population_query = c.acs5.state(("NAME", "B01003_001E"), "36" )
print(ny_population_query)

# Examine the results of the query. Looks like the Census API hands back a list with a dictionary in it, 
# and you have to pull the population info out of that...

[{'NAME': 'New York', 'B01003_001E': 19872319.0, 'state': '36'}]

In [290]:
print(f"The population of New York is: {ny_population_query[0]['B01003_001E']}")

The population of New York is: 19872319.0

In [291]:
# OK now use the state_to_fips dictionary you made in conjunction with the census API 
# to create one more dictionary
# where keys are the state code and values are the population, ie. {"AK":3423908,"AL": .... }

# This might take a while to run! You're pinging an API 50 times. 

state_population = {}    

# Your loop here!

for state in state_to_fips:
    fips = state_to_fips[state]
    pop_query = c.acs5.state(("B01003_001E",), fips)
    state_population[state] = int(pop_query[0]["B01003_001E"])

In [292]:
list(state_population.items())[:5]

[]

I want you to learn to use the Census API because, chances are, it will be useful data to merge/explore as you work on your projects. 

OK. Now back to our data on police shootings. Use pandas and the census library to figure out which state has the highest rate of police killings of disabled people. There isn't one way to get the answer! Think creatively.

In [293]:
# Your code here

# Declare a list

disabled_only = []

# Append w relevant data
for index, row in data.iterrows():
    if row["was_mental_illness_related"] == True:
        disabled_only.append(row)

#Check work
disabled_only_df = pd.DataFrame(disabled_only)
disabled_only_df["was_mental_illness_related"].value_counts(dropna=True)

was_mental_illness_related
True    2057
Name: count, dtype: int64

In [294]:
# Count by state
mental_health_killings_by_state = data.loc[data["was_mental_illness_related"] == True].groupby(
    ["state"]
).size().reset_index(
    name="count"
).sort_values(
    by="count",
    ascending=False
)

mental_health_killings_by_state

   state  count
4     CA    274
43    TX    168
9     FL    166
35    OH     72
47    WA     70
3     AZ     70
27    NC     64
34    NY     63
10    GA     63
42    TN     61
38    PA     52
36    OK     51
22    MI     49
15    IN     49
5     CO     47
37    OR     44
45    VA     43
1     AL     42
24    MO     42
48    WI     38
33    NV     37
18    LA     36
14    IL     35
32    NM     35
20    MD     34
40    SC     30
23    MN     29
44    UT     29
31    NJ     22
17    KY     20
2     AR     20
16    KS     20
19    MA     19
25    MS     17
49    WV     16
30    NH     14
13    ID     12
12    IA     12
41    SD     12
29    NE     11
0     AK     10
26    MT      9
21    ME      8
11    HI      8
28    ND      6
46    VT      6
6     CT      6
50    WY      6
7     DC      5
8     DE      4
39    RI      1

In [295]:
# Add total state population and rate per person

# Build state to fips map
state_to_fips = {}

for state_code, state_info in us_states.items():
    state_to_fips[state_info["code"]] = state_info["fips"]

# Look up state populations
state_population = {}

for state in mental_health_killings_by_state["state"]:
    fips = state_to_fips[state]
    pop_query = c.acs5.state(("B01003_001E",), fips)
    state_population[state] = int(pop_query[0]["B01003_001E"])

# Append w new columns and rank
mental_health_killings_by_state["total_population"] = mental_health_killings_by_state["state"].map(state_population)
mental_health_killings_by_state["rate_per_person"] = mental_health_killings_by_state["count"] / mental_health_killings_by_state["total_population"]

mental_health_killings_by_state.sort_values(by="rate_per_person", ascending=False).head(15)

   state  count  total_population  rate_per_person
32    NM     35           2114768         0.000017
0     AK     10            733971         0.000014
41    SD     12            899194         0.000013
36    OK     51           3995260         0.000013
33    NV     37           3141000         0.000012
37    OR     44           4238714         0.000010
50    WY      6            579761         0.000010
30    NH     14           1387834         0.000010
3     AZ     70           7268175         0.000010
46    VT      6            645254         0.000009
47    WA     70           7740984         0.000009
49    WV     16           1784462         0.000009
42    TN     61           6986082         0.000009
44    UT     29           3331187         0.000009
1     AL     42           5054253         0.000008

Therefore, from 2014 to 2025 New Mexico has the highest rate of police killings related to mental health per resident, at 0.000017.